language: php

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

go:
  - "1.13.x"
  - composer self-update

install:
  - export GO111MODULE=on
  - go mod download
  - composer install --no-interaction --prefer-source

  - go build ./tests/server.go

before_script:
  - ./server &
  - ./server server.sock &

script:
  - go test -v
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config .coveralls.yml
