language: php

sudo: required

php:
  - 7.1

go:
  - 1.8

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - go get "github.com/spiral/goridge"
  - go build tests/server.go
  - go build tests/socket4bytes.go
  - go build tests/socket10echo.go

before_script:
  - ./server &
  - ./socket4bytes &
  - ./socket10echo &
  - ./socket4bytes socket4bytes.sock &
  - ./socket10echo socket10echo.sock &
  - ./server server.sock &

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config .coveralls.yml